export const visaTimelines: Record<string, { compilation: string; processing: string }> = {
  'Visitors Visa 11(1)': { compilation: '1-2 weeks', processing: '4-6 weeks' },
  'Visitors Visa Extension': { compilation: '1-2 weeks', processing: '4-6 weeks' },
  'Critical Skills Work Visa': { compilation: '8-12 weeks', processing: '10-12 weeks' },
  'Critical Skills Visa - Zim Submission': { compilation: '8-12 weeks', processing: '10-12 weeks' },
  'Accompanying Dependent (Spouse)': { compilation: '2-3 weeks', processing: '10-12 weeks' },
  'Spouse Visa': { compilation: '2-3 weeks', processing: '10-12 weeks' },
  'General Work Visa': { compilation: '1-2 weeks', processing: '10-12 weeks' },
  'Waiver Application': { compilation: '1-2 weeks', processing: '4-6 months' },
  "Visitor's Visa Section 11(1)": { compilation: '1-2 weeks', processing: '4-6 weeks' },
  "Visitor's Visa Section 11(1)(b)(ii)": { compilation: '2-3 weeks', processing: '4-6 weeks' },
  "Visitor's Visa Section 11(1)(b)(iii)": { compilation: '2-3 weeks', processing: '10-12 weeks' },
  "Visitor's Visa Section 11(1)(b)(iv)": { compilation: '2-3 weeks', processing: '10-12 weeks' },
  "Visitor's Visa Section 11(2)": { compilation: '1-2 weeks', processing: '15-20 days' },
  'Relatives Visa': { compilation: '2-3 weeks', processing: '6-12 months' },
  'Study Visa': { compilation: '2-3 weeks', processing: '10-12 weeks' },
  'Retired Person Visa': { compilation: '2-3 weeks', processing: '10-12 weeks' },
  'Business Visa': { compilation: '8-10 weeks', processing: '10-12 weeks' },
  'Appeal i.t.o. section 8(4) & 8(6)': { compilation: '<10 days', processing: '4-6 months' },
  'Permanent Residence Permit': { compilation: '3-4 weeks', processing: '>2 years' },
  'Overstay Appeal': { compilation: '<10 days', processing: '10-12 weeks' },
  'Legalisation (Good Cause)': { compilation: '1-2 weeks', processing: '2-3 months' },
  'Prohibition Upliftment': { compilation: '1-2 weeks', processing: '12-18 months' },
  'Proof of Permanent Residence': { compilation: '1-2 weeks', processing: '4-6 weeks' },
  'Citizenship': { compilation: '2-4 weeks', processing: '12-18 months' }
};
